import Head from "next/head";

import { StyledContainer } from "./styles";

const Layout = ({ title = "Next Demo APP", children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledContainer>{children}</StyledContainer>
    </>
  );
};

export default Layout;
